// Very simple server to serve static files on Heroku

delete process.env.BROWSER;

import path from 'path';
import fs from 'fs';

import express from 'express';
import compression from 'compression';
import morgan from 'morgan';
import Handlebars from 'handlebars';

const app = express();

let port = process.env.PORT || 3000;

// Enable Gzip
app.use(compression());

// Serve static cache with the expiry header
app.use(express.static('public', {
  maxAge: 365 * 24 * 60 * 60
}));

// Set default paths to assets
var assetsPaths = { js: 'bundle.js', };

// Developemtn
if (process.env.NODE_ENV === 'development') {
  // Set logger
  app.use(morgan('dev'));
} else {
  // Get assets path from file generated by Webpack
  assetsPaths = require('./public/assets.json');

  // Set logger
  app.use(morgan('combined'));
}

app.use((req, res) => {

  // Generate Handlebars templates
  const indexTpl = Handlebars.compile(fs.readFileSync(path.join(__dirname, 'src', 'index.hbs'), 'utf8'));

  // Respond to all request by the index
  res.end(indexTpl({
    jsPath: assetsPaths.jsPath,
  }));

});

app.listen(port, () => {
  console.log('Server started and listening on port ' + port);
});
